# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 273)
        MainWindow.setStyleSheet("background:green;\n"
"border: 5px solit orange;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.generate_ez = QtWidgets.QPushButton(self.centralwidget)
        self.generate_ez.setGeometry(QtCore.QRect(150, 110, 161, 41))
        self.generate_ez.setStyleSheet("color:purple;\n"
"background:orange;\n"
"border: 2px solid green;\n"
"border-radius: 10px;")
        self.generate_ez.setObjectName("generate_ez")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 95, 13))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.password_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.password_label_2.setGeometry(QtCore.QRect(180, 60, 108, 13))
        self.password_label_2.setObjectName("password_label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 466, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generate_ez.setText(_translate("MainWindow", "oktopis"))
        self.label.setText(_translate("MainWindow", "Генератор паролів"))
        self.password_label_2.setText(_translate("MainWindow", "тут буде ваш пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
